# This workflow builds the source code and deploys to GitHub Pages using Node.js v22.11.0.
# For static site deployment, no dev server or port is required—only the output directory is published.

name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.11.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'npm'

      - run: npm ci

      - name: Build
        run: |
          # If your build needs a specific base path, set it here (e.g., for Vite: npm run build -- --base=/coloring-book/)
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Adjust if your build outputs elsewhere
